id: AEEBEFF4E
base_file: f2A42.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:53:30.542283
  last_modified_at: 2022-05-31 06:53:30.542290
