id: AEEBEFF4E
base_file: fB845.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:53:30.551558
  last_modified_at: 2022-05-31 06:53:30.551565
